# Config file for use with https://github.com/nathanlesage/cheatsheet-generator/
title: Amethyst Keyboard Shortcuts
shortcuts:
  crossplatform:
  darwin:
    Option+Shift: mod1
    Control+Option+Shift: mod2

    Option+Shift+space : Cycle layout forward 
    Control+Option+Shift+space : Cycle layout backwards 
    Option+Shift+h : Shrink the main pane 
    Option+Shift+l : Expand the main pane 
    Option+Shift+, : Increase main pane count 
    Option+Shift+. : Decrease main pane count 
    Option+Shift+j : Move focus counter clockwise 
    Option+Shift+k : Move focus clockwise 
    Option+Shift+p : Move focus to counter clockwise screen 
    Option+Shift+n : Move focus to clockwise screen 
    Control+Option+Shift+h : Swap focused window to counter clockwise screen 
    Control+Option+Shift+l : Swap focused window to clockwise screen 
    Control+Option+Shift+j : Swap focused window counter clockwise 
    Control+Option+Shift+k : Swap focused window clockwise 
    Option+Shift+enter : Swap focused window with main window 
    Option+Shift+z : Force windows to be reevaluated 
    Control+Option+Shift+z : Relaunch Amethyst 
    Control+Option+Shift+left : Throw focused window to space left 
    Control+Option+Shift+right : Throw focused window to space right 
    Control+Option+Shift+1 : Throw focused window to space 1 
    Control+Option+Shift+2 : Throw focused window to space 2 
    Control+Option+Shift+3 : Throw focused window to space 3 
    Control+Option+Shift+4 : Throw focused window to space 4 
    Control+Option+Shift+5 : Throw focused window to space 5 
    Control+Option+Shift+6 : Throw focused window to space 6 
    Control+Option+Shift+7 : Throw focused window to space 7 
    Control+Option+Shift+8 : Throw focused window to space 8 
    Control+Option+Shift+9 : Throw focused window to space 9 
    Control+Option+Shift+0 : Throw focused window to space 10 
    none1     : Throw focused window to space 11 
    none2     : Throw focused window to space 12 
    Option+Shift+w : Focus Screen 1 
    Control+Option+Shift+w : Throw focused window to screen 1 
    Option+Shift+e : Focus Screen 2 
    Control+Option+Shift+e : Throw focused window to screen 2 
    Option+Shift+r : Focus Screen 3 
    Control+Option+Shift+r : Throw focused window to screen 3 
    Option+Shift+q : Focus Screen 4 
    Control+Option+Shift+q : Throw focused window to screen 4 
    Option+Shift+t : Toggle float for focused window 
    Option+Shift+i : Display current layout 
    Control+Option+Shift+t : Toggle global tiling 
    Option+Shift+a : Select tall layout 
    none3 : Select tall-right layout 
    Option+Shift+s : Select wide layout 
    none4 : Select middle-wide layout 
    Option+Shift+d : Select fullscreen layout 
    Option+Shift+f : Select column layout 
    none5 : Select row layout 
    none6 : Select floating layout 
    none7 : Select widescreen-tall layout 
    none8 : Select bsp layout
