disabled_rules:
    - function_body_length
    - closing_brace
    - statement_position
    - force_cast
    - force_try
    - no_space_in_method_call
included:
    - Amethyst
    - AmethystTests
line_length:
    warning: 200
    ignores_comments: true
file_length: 500
type_body_length: 400
cyclomatic_complexity: 15
large_tuple: 3
nesting:
    type_level: 2
identifier_name:
    excluded:
        - id
