# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

lane :mac do
    build_mac_app
    xcodebuild(
        export_archive: true,
        archive_path: "./build/Amethyst.xcarchive",
        export_path: "./build",
        export_options_plist: "./exportOptions.plist"
    )
end
