name: Tests

on:
  push:
    branches: [ development ]
  pull_request:

jobs:
  build:
    name: Build and run unit tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: |
          brew bundle
      - name: Test
        run: |
          set -o pipefail && xcodebuild -workspace Amethyst.xcworkspace -scheme Amethyst clean test | xcbeautify

